version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/home/user/.config
    ports:
      - "8080:8080"
    environment:
      - UID=${UID}
      - GID=${GID}
    command: tail -f /dev/null
